version: 2
registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
  gradle-plugins:
    type: maven-repository
    url: "https://plugins.gradle.org/m2/"

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-google
      - gradle-plugins
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
